### ISSUE TITLE
当每组单元格数量为0时，组头背景色就会失效

### ISSUE THREAD

**Issue by BeingCode** [kingjiajie/JJCollectionViewRoundFlowLayout_Swift#4]

**Comment by kingjiajie** [comment]
您好，你的需求这边是需要如果没有对应cell的时候，也给header或者footer进行计算么？

**Comment by BeingCode** [comment]
@kingjiajie 有可能组头有数据cell为空的情况

**Comment by kingjiajie** [comment]
此前我是限制了这个方案的，这几天我将这个方案也更新上去吧。

**Comment by BeingCode** [comment]
@kingjiajie 非常感谢

**Comment by kingjiajie** [comment]
> @kingjiajie 有可能组头有数据cell为空的情况

该方案已经进行添加。
使用该方案有地方需要注意的：
1、就是Cell个数为0的时候，需要手动开启计算（默认不进行计算的 ）
2、该方案下计算的header&footer还是会受到设置的“header&footer标识或代理影响，控制哪写section进行计算”
3、该方案下，需要特别注意sectionInset设置，当存在header&footer，但Cell个数为0时，计算方式会进行sectionInset计算，从而可能会出现应设置了系统的sectionInset，而看上去header&footer底色多出来了sectionInset的偏移。（当Cell个数为0时，可将对应section的 sectionInset top、bottom设置为0， 或者在JJControlviewFlowLayout上设置回补偏移进行处理。）
