### ISSUE TITLE
项目中用到了RxSwift

### ISSUE THREAD

**Issue by sunKit-io** [kingjiajie/JJCollectionViewRoundFlowLayout_Swift#7]
我项目中用到了rxswift ,导致CollectionViewRoundFlowLayout
<img width="983" alt="image" src="https://user-images.githubusercontent.com/20592158/144953128-bac8f99a-14fa-4678-94c4-288361e4de25.png">
176行 获取的代理为rx的代理，请问这个如何兼容呢

**Comment by kingjiajie** [comment]
如果使用RxSwift的情况下，暂时这个还在构思解决方案中，后期可能使用扩展方案解决，但是现在暂时没有好的方案呢，

**Comment by sunKit-io** [comment]
> 如果使用RxSwift，这个解决方案还在构思中，可能使用扩展方案解决，但现在没有好的方案。

好的，现在已经讲rx 去掉了，感谢
