### ISSUE TITLE
分区添加渐变色或者渐变图片

### ISSUE THREAD

**Issue by luo-h** [kingjiajie/JJCollectionViewRoundFlowLayout_Swift#8]
提个小小需求，要是可以分区显示渐变色就完美了

**Comment by kingjiajie** [comment]
> 提个小小需求，要是可以分区显示渐变色就完美了

您好，感谢您的提议，渐变色是可以添加的，我看看后续是否增加该方案，看如果添加渐变色需要对外增加多少配置项等信息。
另外，现在也是可以处理渐变色的，因为已经是支持使用image做图片显示，可以先绘画一个渐变的image做底图实现渐变效果。

**Comment by luo-h** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by luo-h** [comment]
好的，谢谢，可以使用图片吗，我看JJCollectionViewRoundConfigModel_Swift这个类没有图片参数呢

**Comment by kingjiajie** [comment]
> 好的，谢谢，可以使用图片吗，我看JJCollectionViewRoundConfigModel_Swift这个类没有图片参数呢

不好意思，我看了下，OC那边的库更新了，swift没有更新到，这两天图片方面等其他新增的内容我进行一下同步。到时候图片方面也会同步上去的。至于渐变色方面，需要调研一下如果做优化方案，才能做增加功能处理。感谢您的回复。
